spring:
  kafka:
    consumer:
      bootstrap-servers: k7a606.p.ssafy.io:9092
      enable-auto-commit: false
      auto-offset-reset: earliest
    listener:
      type: batch
      ack-mode: manual_immediate
  data:
    mongodb:
      port: 27017
      host: k7a606.p.ssafy.io
      database: cseon
