spring:
  redis:
    port: 6379
    host: k7a606.p.ssafy.io
  kafka:
    consumer:
      bootstrap-servers: k7a606.p.ssafy.io:9092
      enable-auto-commit: false
      auto-offset-reset: earliest
    listener:
      ack-mode: manual_immediate
      type: batch
