spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: cseon
  kafka:
    consumer:
      bootstrap-servers: localhost:9092
      enable-auto-commit: false
      auto-offset-reset: earliest
    listener:
      type: batch